version: '3'
services:
  ui:
    build: .
    ports:
      - '12345:80'
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - api
  
  api:
    build: api/
    command: gtasks-api
    volumes:
      - ./sandbox/db:/db
